[package]
name = "linkerd-tls-rustls"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
futures = { version = "0.3", default-features = false }
linkerd-error = { path = "../../error" }
linkerd-io = { path = "../../io" }
linkerd-proxy-identity = { path = "../../proxy/identity" }
linkerd-stack = { path = "../../stack" }
linkerd-tls = { path = ".." }
ring = { version = "0.16.19", features = ["std"] }
thiserror = "1"
tokio = { version = "1", features = ["sync"] }
tokio-rustls = "0.22"
tracing = "0.1"
webpki = "0.21"

[dev-dependencies]
linkerd-conditional = { path = "../../conditional" }
linkerd-proxy-transport = { path = "../../proxy/transport" }
linkerd-tls-test-util = { path = "../test-util" }
linkerd-tracing = { path = "../../tracing", features = ["ansi"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.10", default-features = false, features = ["util"] }
