name: CIFuzz
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@570c150a0543d8b1a848da70caef208db0e1c3ba
      with:
        oss-fuzz-project-name: 'linkerd2-proxy'
        dry-run: false
        language: rust
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@570c150a0543d8b1a848da70caef208db0e1c3ba
      with:
        oss-fuzz-project-name: 'linkerd2-proxy'
        fuzz-seconds: 600
        dry-run: false
        language: rust
    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
